### ISSUE TITLE
Update TUK to the latest version

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/payload-tsat#33]
## 📋 Task Description
**Summary**
Finish upgrading TUK on the `feat/upgrade-tuk` branch in Payload.

**Details**
A while ago we made a bunch of changes to the TSAT Utilities Kit. We made a lot of API changes and made it require RTOS to use.

These changes mean our old code in the Payload firmware is now incompatible. To fix this, I started a branch where I was updating the Payload code to be compatible with the new version of the TUK API.

Unfortunately, I never finished as I got busy with other things. For this task, please complete the migration to the latest commit of TUK.

The new code will definitely not be 1:1 with the old code, as there were quite a few changes in the new API.

To make things easier for you, here is a step-by-step process on how to do this:
1. Using Git, update the TUK submodule to the latest commit (Look up submodules and git commands if you don't know how to do this).
2. Try to compile using STM32CubeIDE (Let me know if you need help setting this up).
3. You will see lots of errors mostly likely. This is where your investigation skills come into play (and asking questions!!). Use the **Notes/References** section in case there's anything you need to read up on. For example, you will have to enable RTOS in Payload as it's required in the new version of TUK.
4. Go through the list of errors and fix each one independently. Take notes on things you're not sure about and bring them up in an upcoming Software meeting. Do not hesitate to ask questions in the #s-software channel for additional assistance. I don't expect someone brand new to be able to complete this task all on their own.

## ✅ Completion Criteria
- [ ] The submodule for TUK is at the latest commit.
- [ ] The updated Payload code has been reviewed by @Koloss0 or @ArnavG-it.
- [ ] The code compiles with no errors (and ideally no warnings).
- [ ] You learned something new! 🙂

## 📂 Affected Components
- Only [Payload-MCU](https://github.com/UMSATS/payload-tsat/tree/feat/upgrade-tuk/Payload-MCU) will be affected.

## 🚧 Notes / Reference
- The TSAT Utilities Kit Wiki includes an [Installation Instructions](https://github.com/UMSATS/tsat-utilities-kit/wiki#installation) page, which mentions how to enable RTOS for your STM32 project in step 6. You will need to follow these steps when setting up RTOS for Payload.
- What is RTOS? It stands for [Real-Time Operating System](https://en.wikipedia.org/wiki/Real-time_operating_system). Feel free to read up on it to understand it better. But in essence, it provides an API for multitasking. In other words, we can have multiple threads at once fulfilling different responsibilities. It shouldn't be relevant, but just in case, here's some documentation on the API we use: [CMSIS V2 Documentation](https://arm-software.github.io/CMSIS_5/RTOS2/html/index.html)
- The [CAN Wrapper Usage Guide](https://github.com/UMSATS/tsat-utilities-kit/wiki/CAN-Wrapper-Module-Usage-Guide) demonstrates the usage of TUK. Feel free to reference it as you're writing the Payload code.
- The [TSAT-7 Command Reference](https://docs.google.com/spreadsheets/d/1fF_nCTbqJ7y3KoorSmB4DAGctDv61TSHfD0VK8CovCM/edit?gid=1728821240#gid=1728821240) lists all CAN commands we expect to have on the satellite, including Payload. As you're updating TUK, you may have to adjust the names, but I'm not sure. But there you have it, just in case!
- For more examples of TUK being used in practice, check out the [SOTI board code on the `refactor/update-tuk` branch](https://github.com/UMSATS/soti/blob/refactor/update-soti-board-code/soti-board-project/App/Src/app.c), which uses TUK for sending and receiving CAN messages.
